### ISSUE TITLE
Dark mode icons not visable

### ISSUE THREAD

**Issue by djrwp** [artur-burkalo/destiny-elements#1]
Dark mode icons need to switch to white.
<img width="277" alt="Screenshot 2022-12-07 at 10 10 26" src="https://user-images.githubusercontent.com/84224815/206151110-c018412c-3272-4d34-a30a-4a3df79e1871.png">

**Comment by artur-burkalo** [comment]
Thanks for the reporting the dark mode issue, this will be fixed in the next release.
