### ISSUE TITLE
&amp; displayed in title for dropdown checkboxes

### ISSUE THREAD

**Issue by lockedm** [artur-burkalo/destiny-elements#13]
When categories are something like "apples & oranges", this displayed correctly in the dropdown, but in the dropdown title, this is displayed as "apples &amp; oranges". See screenshot:

![image](https://github.com/Destiny-Elements/destiny-elements-pub/assets/112517932/072a8a07-c083-4026-8f5e-dadc2ab7293d)

**Comment by artur-burkalo** [comment]
This is fixed and now in development and will be released in version 1.6.3.
