### ISSUE TITLE
Bug: Can't activate hotspots in images via keyboard

### ISSUE THREAD

**Issue by rpaasch** [artur-burkalo/destiny-elements#14]
I'm attempting to implement keyboard-only navigation as I develop websites for individuals with disabilities. While testing the image hotspots, I'm encountering an issue where I can't trigger the pop-up when using the spacebar or enter key. This is problematic because users who rely on screen readers won't be able to access the pop-up.

**Comment by artur-burkalo** [comment]
This is fixed in the development, and will be out in the next release. We have also included an Escape key to close the popups.
