### ISSUE TITLE
Table element display error

### ISSUE THREAD

**Issue by federicrosa** [artur-burkalo/destiny-elements#23]
Hi, the table element has a display problem in version 1.8.6. In fact, every time you insert data into a row or column, it is duplicated. See screenshot.

<img width="1512" alt="Screenshot 2024-08-29 alle 21 56 08" src="https://github.com/user-attachments/assets/9289a1b4-61b5-4526-8b56-55cf0a47b80b">

**Comment by hanas879** [comment]
Same problem here! I tough I was going crazy and had done something wrong but couldn't find any problems... heh

**Comment by artur-burkalo** [comment]
This has been just released in version 1.8.7 that resolves the bug.
